export const TICKETS_LOADING_BEGIN = 'TICKETS_LOADING_BEGIN'
export const TICKETS_LOADING_SUCCESS = 'TICKETS_LOADING_SUCCESS'
export const TICKETS_LOADING_FAIL = 'TICKETS_LOADING_FAIL'

export const CHANGE_FILTER = 'CHANGE_FILTER'
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'

